# Sentinel v1 — © 2026 Ben Duske. Licensed under the MIT License (see LICENSE).
"""Report export — Markdown now; PDF is a thin optional add (reportlab)."""
import datetime
import math


def _fmt_when(inc: dict) -> str:
    """Format created_at defensively — "unknown" when it's missing/null/non-numeric.

    Every other report field degrades gracefully to a placeholder ("(untitled)", "unscored",
    "—"); created_at was the lone exception. A stored-but-null created_at (valid JSON, reachable
    via a hand-edit / partial migration / foreign writer — the store column has no NOT NULL
    constraint and save() persists None) made ``fromtimestamp(None)`` raise TypeError, crashing
    the customer-facing export with a 500; an absent key silently rendered a misleading 1969 epoch
    date. Coerce to a real, finite number and fall back to "unknown" otherwise — behaviour-
    identical for every normally-created incident (created_at is always a valid float).
    """
    ts = inc.get("created_at")
    if isinstance(ts, bool) or not isinstance(ts, (int, float)) or not math.isfinite(ts):
        return "unknown"
    try:
        return datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")
    except (ValueError, OverflowError, OSError):
        return "unknown"


def to_markdown(inc: dict) -> str:
    when = _fmt_when(inc)
    # `or []` guards a stored-but-null recommended_actions/evidence (valid JSON, reachable via a
    # hand-edit / partial migration / foreign writer — the store has no NOT NULL constraint) that
    # would otherwise make enumerate(None) raise TypeError and 500 this primary export. The PDF
    # renderer already coerces both this way; keep the two export paths at parity.
    actions = "\n".join(f"{i}. {a}" for i, a in enumerate(inc.get("recommended_actions") or [], 1))
    evidence = "\n".join(f"- {e}" for e in (inc.get("evidence") or [])) or "_none attached_"
    return f"""# Incident Report — {inc.get('title','(untitled)')}

**ID:** `{inc.get('id')}`  **Reported:** {when}  **Status:** {inc.get('status')}

## Severity: {str(inc.get('severity') or 'unscored').upper()}
{inc.get('severity_rationale','')}

## Summary
{inc.get('summary') or inc.get('description','')}

## Recommended actions
{actions or '_none_'}

## Evidence
{evidence}

---
_Generated by Sentinel v1 — local AI risk & incident intelligence. AI-assisted; reviewed by a human before use._
"""


def to_pdf(inc: dict, path: str) -> bool:
    """Best-effort PDF via reportlab if installed; returns False if unavailable.

    Renders a clean, professional incident report (title, severity badge, rationale, summary,
    numbered actions, evidence, disclaimer footer) using reportlab's Platypus flowables. When
    reportlab is absent the caller surfaces a graceful 501 — the PDF path is never required.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_LEFT
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )
    except Exception:
        return False

    def _esc(s) -> str:
        return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))

    sev = str(inc.get("severity", "") or "unscored").lower()
    sev_color = {
        "low": colors.HexColor("#16a34a"),
        "medium": colors.HexColor("#d97706"),
        "high": colors.HexColor("#ea580c"),
        "critical": colors.HexColor("#dc2626"),
    }.get(sev, colors.HexColor("#64748b"))

    when = _fmt_when(inc)
    styles = getSampleStyleSheet()
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=10.5, leading=15,
                          alignment=TA_LEFT, spaceAfter=4)
    h_title = ParagraphStyle("h_title", parent=styles["Title"], fontSize=20, leading=24,
                             spaceAfter=2, textColor=colors.HexColor("#0f172a"))
    h_sec = ParagraphStyle("h_sec", parent=styles["Heading2"], fontSize=13, leading=16,
                           spaceBefore=12, spaceAfter=4, textColor=colors.HexColor("#1e293b"))
    meta = ParagraphStyle("meta", parent=styles["Normal"], fontSize=9, leading=12,
                          textColor=colors.HexColor("#64748b"))
    foot = ParagraphStyle("foot", parent=styles["Normal"], fontSize=8, leading=11,
                          textColor=colors.HexColor("#94a3b8"))

    doc = SimpleDocTemplate(path, pagesize=letter, title=f"Incident Report — {inc.get('title','')}",
                            author="Sentinel v1 — Ben Duske",
                            leftMargin=0.9 * inch, rightMargin=0.9 * inch,
                            topMargin=0.8 * inch, bottomMargin=0.8 * inch)
    flow = []
    flow.append(Paragraph("Sentinel — Incident Report", meta))
    flow.append(Paragraph(_esc(inc.get("title", "(untitled)")), h_title))
    flow.append(Paragraph(
        f"ID: {_esc(inc.get('id'))} &nbsp;&bull;&nbsp; Reported: {when} "
        f"&nbsp;&bull;&nbsp; Status: {_esc(inc.get('status'))}", meta))
    flow.append(Spacer(1, 8))

    # Severity badge as a small colored table cell.
    badge = Table([[Paragraph(f"SEVERITY: {sev.upper()}",
                              ParagraphStyle("badge", parent=body, textColor=colors.white,
                                             fontName="Helvetica-Bold", fontSize=11))]],
                  colWidths=[2.4 * inch])
    badge.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), sev_color),
        ("LEFTPADDING", (0, 0), (-1, -1), 10), ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    flow.append(badge)
    flow.append(Spacer(1, 6))

    if inc.get("severity_rationale"):
        flow.append(Paragraph("Why this severity (grounded rule layer + AI judgment)", h_sec))
        flow.append(Paragraph(_esc(inc["severity_rationale"]), body))

    flow.append(Paragraph("Summary", h_sec))
    flow.append(Paragraph(_esc(inc.get("summary") or inc.get("description", "") or "—"), body))

    flow.append(Paragraph("Recommended actions", h_sec))
    actions = inc.get("recommended_actions", []) or []
    if actions:
        for i, a in enumerate(actions, 1):
            flow.append(Paragraph(f"{i}. {_esc(a)}", body))
    else:
        flow.append(Paragraph("—", body))

    flow.append(Paragraph("Evidence", h_sec))
    evidence = inc.get("evidence", []) or []
    if evidence:
        for e in evidence:
            flow.append(Paragraph(f"&bull; {_esc(e)}", body))
    else:
        flow.append(Paragraph("None attached.", body))

    flow.append(Spacer(1, 16))
    flow.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1")))
    flow.append(Spacer(1, 4))
    flow.append(Paragraph(
        "Generated by Sentinel v1 — local AI risk &amp; incident intelligence. "
        "AI-assisted decision-support, not an authoritative underwriting or safety "
        "determination; reviewed by a human before use.", foot))

    doc.build(flow)
    return True
