# Sentinel v1 — © 2026 Ben Duske. Licensed under the MIT License (see LICENSE).
"""Report export — Markdown now; PDF is a thin optional add (reportlab)."""
import datetime


def to_markdown(inc: dict) -> str:
    when = datetime.datetime.fromtimestamp(inc.get("created_at", 0)).strftime("%Y-%m-%d %H:%M")
    actions = "\n".join(f"{i}. {a}" for i, a in enumerate(inc.get("recommended_actions", []), 1))
    evidence = "\n".join(f"- {e}" for e in inc.get("evidence", [])) or "_none attached_"
    return f"""# Incident Report — {inc.get('title','(untitled)')}

**ID:** `{inc.get('id')}`  **Reported:** {when}  **Status:** {inc.get('status')}

## Severity: {str(inc.get('severity','')).upper()}
{inc.get('severity_rationale','')}

## Summary
{inc.get('summary') or inc.get('description','')}

## Recommended actions
{actions or '_none_'}

## Evidence
{evidence}

---
_Generated by Sentinel v1 — local AI risk & incident intelligence. AI-assisted; reviewed by a human before use._
"""


def to_pdf(inc: dict, path: str) -> bool:
    """Best-effort PDF via reportlab if installed; returns False if unavailable."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except Exception:
        return False
    c = canvas.Canvas(path, pagesize=letter)
    y = 760
    for line in to_markdown(inc).splitlines():
        c.drawString(54, y, line[:110])
        y -= 14
        if y < 54:
            c.showPage(); y = 760
    c.save()
    return True
